"use client";
import { useState } from "react";

type Props={documents:{id:string,name:string}[];schedules:{id:string,name:string,frequency:string,active:boolean,nextRunAt:string|null,lastRunAt:string|null}[];alerts:{id:string,title:string,severity:string,status:string,createdAt:string|null}[]};
export default function MonitoringClient({documents,schedules:initial,alerts}:Props){
 const [schedules,setSchedules]=useState(initial); const [name,setName]=useState("Weekly compliance review"); const [frequency,setFrequency]=useState("WEEKLY"); const [selected,setSelected]=useState<string[]>(documents.slice(0,1).map(x=>x.id)); const [busy,setBusy]=useState(false);
 async function create(){setBusy(true);const r=await fetch("/api/monitoring/schedules",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name,frequency,documentIds:selected})});if(r.ok) location.reload();else alert((await r.json()).error);setBusy(false)}
 async function toggle(id:string,active:boolean){await fetch(`/api/monitoring/schedules/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({active:!active})});setSchedules(schedules.map(x=>x.id===id?{...x,active:!active}:x));}
 return <div className="mt-8 space-y-8">
  <section className="rounded-xl border bg-white p-6"><h2 className="font-semibold">Create monitoring schedule</h2><div className="mt-4 grid gap-4 md:grid-cols-3"><input value={name} onChange={e=>setName(e.target.value)} className="rounded border p-2"/><select value={frequency} onChange={e=>setFrequency(e.target.value)} className="rounded border p-2"><option value="DAILY">Daily</option><option value="WEEKLY">Weekly</option><option value="MONTHLY">Monthly</option></select><button disabled={!selected.length||busy} onClick={create} className="rounded bg-slate-950 px-4 py-2 text-white disabled:opacity-40">{busy?"Creating…":"Create schedule"}</button></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{documents.map(d=><label key={d.id} className="flex items-center gap-2 rounded border p-3 text-sm"><input type="checkbox" checked={selected.includes(d.id)} onChange={e=>setSelected(e.target.checked?[...selected,d.id]:selected.filter(x=>x!==d.id))}/>{d.name}</label>)}</div></section>
  <section className="rounded-xl border bg-white divide-y"><div className="p-5 font-semibold">Schedules</div>{!schedules.length&&<div className="p-5 text-sm text-slate-500">No monitoring schedules yet.</div>}{schedules.map(x=><div key={x.id} className="flex items-center justify-between gap-4 p-5"><div><div className="font-medium">{x.name}</div><div className="mt-1 text-xs text-slate-500">{x.frequency} · next {x.nextRunAt?new Date(x.nextRunAt).toLocaleString():"—"}</div></div><button onClick={()=>toggle(x.id,x.active)} className="rounded border px-3 py-2 text-sm">{x.active?"Pause":"Resume"}</button></div>)}</section>
  <section className="rounded-xl border bg-white divide-y"><div className="p-5 font-semibold">Monitoring alerts</div>{!alerts.length&&<div className="p-5 text-sm text-slate-500">No alerts yet.</div>}{alerts.map(a=><div key={a.id} className="p-5"><div className="flex justify-between"><span className="font-medium">{a.title}</span><span className="text-xs font-semibold">{a.severity}</span></div><div className="mt-1 text-xs text-slate-500">{a.status} · {a.createdAt?new Date(a.createdAt).toLocaleString():""}</div></div>)}</section>
 </div>
}
